---
- name: create guides project
  when: num_users | int > 0
  k8s:
    state: present
    kind: Project
    api_version: project.openshift.io/v1
    definition:
      metadata:
        name: "guides"
        annotations:
          openshift.io/description: ""
          openshift.io/display-name: "Fuse Workshop Guides"

- name: search for username distribution tool
  k8s_info:
    kind: DeploymentConfig
    name: get-a-username
    namespace: guides
  register: r_gau_dc

- name: search for Redis
  k8s_info:
    kind: DeploymentConfig
    name: redis
    namespace: guides
  register: r_redis_dc

- name: deploy redis
  when:
    - r_gau_dc.resources | list | length == 0
    - r_redis_dc.resources | list | length == 0
  shell: >
    oc process -f -
    -p DATABASE_SERVICE_NAME=redis
    -p REDIS_PASSWORD=redis
    -p VOLUME_CAPACITY=1Gi
    -p MEMORY_LIMIT=1Gi
    -p REDIS_VERSION=5
    | oc create -n guides  -f -
  args:
    stdin: "{{ lookup('file', './files/redis-template.yaml') }}"

- name: wait for redis to be ready
  when: r_gau_dc.resources | list | length == 0
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: guides
    label_selectors:
      - name = redis
      - deploymentconfig = redis
    field_selectors:
      - status.phase=Running
  register: r_redis_pod
  retries: 120
  delay: 10
  until: r_redis_pod.resources | list | length == 1

- name: deploy username distribution tool
  when: r_gau_dc.resources | list | length == 0
  shell: >
    oc -n guides new-app --as-deployment-config quay.io/openshiftlabs/username-distribution:1.4 --name=get-a-username
    -e LAB_REDIS_HOST=redis
    -e LAB_REDIS_PASS=redis
    -e LAB_TITLE={{ 'Fuse Workshop' | quote }}
    -e LAB_DURATION_HOURS=1week
    -e LAB_USER_COUNT={{ num_users }}
    -e LAB_USER_ACCESS_TOKEN={{ workshop_openshift_user_password }}
    -e LAB_USER_PASS={{ workshop_openshift_user_password }}
    -e LAB_USER_PREFIX=user
    -e LAB_USER_PAD_ZERO=false
    -e LAB_ADMIN_PASS={{ workshop_openshift_user_password }}
    -e LAB_MODULE_URLS='https://{{ webapp_secure_route }};Solution Explorer'
    -e LAB_EXTRA_URLS='{{console_url}}/topology/ns/user1-project;OpenShift Console,https://codeready-codeready.{{ route_subdomain}};CodeReady Workspaces Console'

- name: expose username distribution tool
  when: r_gau_dc.resources | list | length == 0
  k8s:
    api_version: route.openshift.io/v1
    namespace: guides
    state: present
    kind: Route
    definition:
      metadata:
        name: get-a-username
        labels:
          app: get-a-username
      spec:
        host: ''
        to:
          kind: Service
          name: get-a-username
          weight: 100
        port:
          targetPort: 8080-tcp
        tls:
          termination: edge
          insecureEdgeTerminationPolicy: Allow
  register: Route
