---
- name: create usernames
  set_fact:
    users: "{{ ['user'+item | string] }}"
  loop: "{{ range(1,((num_users | int) + 1)) | list }}"

- name: create projects for users
  include_tasks: create_project.yaml
  vars:
    t_project_name: "{{ t_user }}-project"
  loop: "{{ users }}"
  loop_control:
    loop_var: t_user

- name: install username distribution
  when: num_users | int > 0
  include_tasks: install-username-distribution.yaml

# Install CRW via operator
- name: see if codeready is installed
  k8s_info:
    api_version: org.eclipse.che/v1
    kind: CheCluster
    name: codeready-workspaces
    namespace: codeready
  register: r_codeready_cr

- name: show codeready cr
  debug:
    msg: "existing codeready project: {{ r_codeready_cr }}"

- name: install codeready
  when: r_codeready_cr.resources | list | length == 0
  include_tasks: install-codeready.yaml
